
// import { useEffect, useState, useCallback } from "react";
// import api from "../../../api/api";
// import Layout from "../../Layout/Layout";
// import StatusBadge from "../../Common/StatusBadge";
// import Paginator from "../../Common/Paginator";

// const PAGE_SIZE = 10;
// const STATUSES = ["All", "Generated", "Paid" , "Pending"];

// const Invoices = () => {
//   const [allInvoices,  setAllInvoices]  = useState([]);
//   const [loading,      setLoading]      = useState(true);
//   const [search,       setSearch]       = useState("");
//   const [statusFilter, setStatusFilter] = useState("All");
//   const [page,         setPage]         = useState(1);
//   const [toast,        setToast]        = useState(null);

//   const showToast = (msg, type = "success") => {
//     setToast({ msg, type });
//     setTimeout(() => setToast(null), 3000);
//   };

//   const load = useCallback(async () => {
//     setLoading(true);
//     try {
//       const res = await api.get("/api/Invoice/provider");
//       const items = Array.isArray(res.data) ? res.data : (res.data?.items ?? []);
//       setAllInvoices(items);
//     } catch {
//       showToast("Failed to load invoices.", "danger");
//     } finally {
//       setLoading(false);
//     }
//   }, []);

//   useEffect(() => { load(); }, [load]);

//   const filtered = allInvoices.filter(inv => {
//     const s = search.toLowerCase();
//     const matchSearch = !search ||
//       (inv.invoiceNumber || "").toLowerCase().includes(s) ||
//       (inv.patientName   || "").toLowerCase().includes(s);
//     const invStatus = inv.invoiceStatus || "Generated";
//     const matchStatus = statusFilter === "All" || invStatus === statusFilter;
//     return matchSearch && matchStatus;
//   });

//   const totalCount = filtered.length;
//   const totalPages = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));
//   const visible    = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

//   const handleSearch = (val) => { setSearch(val); setPage(1); };
//   const handleStatus = (val) => { setStatusFilter(val); setPage(1); };

//   const formatDate = (d) => {
//     if (!d) return "—";
//     return new Date(d).toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" });
//   };

//   return (
//     <Layout role="provider">

//       {toast && (
//         <div className={`alert alert-${toast.type} position-fixed top-0 end-0 m-3 shadow`} style={{ zIndex: 9999 }}>
//           {toast.msg}
//         </div>
//       )}

//       {/* Header */}
//       <div className="mb-4">
//         <h4 className="fw-bold mb-1">Invoices</h4>
//         <p className="text-muted small mb-0">All invoices generated by your hospital</p>
//       </div>

//       {/* Search + Status filter */}
//       <div className="card border-0 shadow-sm mb-4">
//         <div className="card-body d-flex flex-wrap gap-3 align-items-center py-3">
//           <input
//             className="form-control"
//             style={{ maxWidth: 320 }}
//             placeholder="Search by invoice # or patient name…"
//             value={search}
//             onChange={e => handleSearch(e.target.value)}
//           />
//           <div className="d-flex flex-wrap gap-2">
//             {STATUSES.map(s => (
//               <button key={s}
//                 className={`btn btn-sm ${statusFilter === s ? "btn-primary" : "btn-outline-secondary"}`}
//                 onClick={() => handleStatus(s)}>
//                 {s}
//               </button>
//             ))}
//           </div>
//         </div>
//       </div>

//       {/* Table */}
//       <div className="card border-0 shadow-sm">
//         <div className="table-responsive">
//           <table className="table table-hover align-middle mb-0">
//             <thead className="table-light">
//               <tr>
//                 <th>Invoice #</th>
//                 <th>Patient</th>
//                 <th>Amount</th>
//                 <th>Date</th>
//                 <th>Status</th>
//               </tr>
//             </thead>
//             <tbody>
//               {loading ? (
//                 <tr>
//                   <td colSpan={5} className="text-center py-5">
//                     <div className="spinner-border spinner-border-sm text-primary me-2" />
//                     Loading invoices…
//                   </td>
//                 </tr>
//               ) : visible.length === 0 ? (
//                 <tr>
//                   <td colSpan={5} className="text-center py-5 text-muted">No invoices found.</td>
//                 </tr>
//               ) : visible.map(inv => (
//                 <tr key={inv.invoiceId}>
//                   <td className="fw-semibold">{inv.invoiceNumber || `#${inv.invoiceId}`}</td>
//                   <td>{inv.patientName || "—"}</td>
//                   <td>₹{(inv.totalAmount ?? 0).toLocaleString("en-IN")}</td>
//                   <td className="text-muted small">{formatDate(inv.invoiceDate)}</td>
//                   <td><StatusBadge status={inv.invoiceStatus || "Generated"} /></td>
//                 </tr>
//               ))}
//             </tbody>
//           </table>
//         </div>

//         <Paginator
//           page={page}
//           totalPages={totalPages}
//           totalCount={totalCount}
//           pageSize={PAGE_SIZE}
//           onPageChange={setPage}
//         />
//       </div>

//     </Layout>
//   );
// };

// export default Invoices;


import { useEffect, useState, useCallback } from "react";
import { FileText, User, Calendar, Hash, Search, IndianRupee } from "lucide-react";
import api from "../../../api/api";
import Layout from "../../Layout/Layout";
import StatusBadge from "../../Common/StatusBadge";
import Paginator from "../../Common/Paginator";

const PAGE_SIZE = 10;
const STATUSES  = ["All", "Generated", "Paid", "Pending"];

/* ─── Styles ─────────────────────────────────────────────────────────── */
const styles = `
  @import url('https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

  .inv-root {
    font-family: 'Sora', sans-serif;
    --teal:       #0d9488;
    --teal-light: #ccfbf1;
    --teal-dark:  #0f766e;
    --green:      #22c55e;
    --green-light:#dcfce7;
    --amber:      #f59e0b;
    --amber-light:#fef3c7;
    --slate:      #64748b;
    --ink:        #0f172a;
    --surface:    #f8fafc;
    --card-bg:    #ffffff;
    --border:     #e2e8f0;
    --radius:     14px;
    --shadow:     0 1px 3px rgba(0,0,0,.06), 0 4px 16px rgba(0,0,0,.06);
    --shadow-hover: 0 4px 12px rgba(13,148,136,.12), 0 8px 28px rgba(0,0,0,.08);
  }

  /* ── header ── */
  .inv-header { margin-bottom: 2rem; }
  .inv-header h2 { font-size:1.6rem; font-weight:700; color:var(--ink); margin:0 0 .25rem; letter-spacing:-.02em; }
  .inv-header p  { font-size:.82rem; color:var(--slate); margin:0; }

  /* ── stat strip ── */
  .inv-stats { display:grid; grid-template-columns:repeat(auto-fill,minmax(160px,1fr)); gap:.85rem; margin-bottom:1.75rem; }
  .stat-card {
    background:var(--card-bg); border:1px solid var(--border);
    border-radius:var(--radius); padding:.9rem 1.1rem;
    box-shadow:var(--shadow); display:flex; flex-direction:column; gap:.3rem;
  }
  .stat-card .stat-label { font-size:.75rem; color:var(--slate); font-weight:500; }
  .stat-card .stat-value { font-size:1.35rem; font-weight:700; color:var(--ink); font-family:'JetBrains Mono',monospace; }
  .stat-card .stat-sub   { font-size:.72rem; color:var(--slate); }

  /* ── toolbar ── */
  .inv-toolbar {
    background:var(--card-bg); border:1px solid var(--border);
    border-radius:var(--radius); padding:1rem 1.25rem;
    display:flex; flex-wrap:wrap; gap:.75rem; align-items:center;
    margin-bottom:1.5rem; box-shadow:var(--shadow);
  }
  .status-pill {
    border-radius:8px; padding:.38rem .8rem;
    font-size:.8rem; font-weight:600; cursor:pointer;
    border:1.5px solid var(--border); background:#fff; color:var(--slate);
    transition:all .18s;
  }
  .status-pill.active { background:var(--teal); color:#fff; border-color:var(--teal); }
  .inv-search { margin-left:auto; position:relative; min-width:220px; max-width:300px; flex:1; }
  .inv-search input {
    width:100%; border:1.5px solid var(--border); border-radius:9px;
    padding:.42rem .8rem .42rem 2.2rem; font-size:.82rem; font-family:'Sora',sans-serif;
    background:var(--surface); color:var(--ink); outline:none; transition:border-color .2s; box-sizing:border-box;
  }
  .inv-search input:focus { border-color:var(--teal); }
  .inv-search svg { position:absolute; left:.6rem; top:50%; transform:translateY(-50%); color:var(--slate); }

  /* ── cards grid ── */
  .inv-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(310px,1fr)); gap:1rem; }

  .inv-card {
    background:var(--card-bg); border:1px solid var(--border);
    border-radius:var(--radius); padding:1.25rem 1.35rem;
    box-shadow:var(--shadow); position:relative; overflow:hidden;
    transition:box-shadow .2s, transform .2s; display:flex; flex-direction:column; gap:.75rem;
  }
  .inv-card:hover { box-shadow:var(--shadow-hover); transform:translateY(-2px); }
  .inv-card::before {
    content:''; position:absolute; left:0; top:0; bottom:0;
    width:4px; border-radius:4px 0 0 4px;
  }
  .inv-card.generated::before { background:var(--teal); }
  .inv-card.paid::before      { background:var(--green); }
  .inv-card.pending::before   { background:var(--amber); }

  .inv-card-top { display:flex; justify-content:space-between; align-items:flex-start; }
  .inv-number { font-family:'JetBrains Mono',monospace; font-size:.78rem; font-weight:500; color:var(--teal); }

  .inv-amount-badge {
    background:var(--teal-light); color:var(--teal-dark);
    border-radius:8px; padding:.28rem .7rem;
    font-size:.85rem; font-weight:700; font-family:'JetBrains Mono',monospace;
    display:inline-flex; align-items:center; gap:.3rem;
  }
  .inv-amount-badge.paid { background:var(--green-light); color:#15803d; }
  .inv-amount-badge.pending { background:var(--amber-light); color:#92400e; }

  .inv-meta { display:flex; flex-direction:column; gap:.35rem; }
  .inv-meta-row { display:flex; align-items:center; gap:.5rem; font-size:.82rem; color:var(--slate); }
  .inv-meta-row svg { color:var(--teal); flex-shrink:0; }
  .inv-meta-row strong { color:var(--ink); font-weight:600; }

  .inv-card-footer {
    display:flex; justify-content:space-between; align-items:center;
    padding-top:.65rem; border-top:1px solid var(--border);
  }
  .inv-date-chip {
    display:flex; align-items:center; gap:.35rem;
    font-size:.75rem; color:var(--slate);
  }
  .inv-date-chip svg { color:var(--teal); }

  /* ── empty / loading ── */
  .inv-empty {
    text-align:center; padding:4rem 2rem; color:var(--slate);
    background:var(--card-bg); border:1px solid var(--border);
    border-radius:var(--radius); box-shadow:var(--shadow);
  }
  .inv-empty svg { display:block; margin:0 auto .75rem; opacity:.3; }
  .inv-loading { display:flex; justify-content:center; align-items:center; gap:.6rem; padding:3rem; color:var(--slate); font-size:.9rem; }
  .spinner { width:20px; height:20px; border:2.5px solid var(--border); border-top-color:var(--teal); border-radius:50%; animation:spin .7s linear infinite; }
  @keyframes spin { to { transform:rotate(360deg); } }

  /* ── toast ── */
  .inv-toast {
    position:fixed; top:1rem; right:1rem; z-index:9999;
    padding:.75rem 1.2rem; border-radius:10px; font-size:.84rem; font-weight:500;
    box-shadow:0 4px 20px rgba(0,0,0,.15); animation:slideIn .25s ease;
  }
  .inv-toast.success { background:var(--teal); color:#fff; }
  .inv-toast.danger  { background:#ef4444;    color:#fff; }
  @keyframes slideIn { from { opacity:0; transform:translateX(12px); } to { opacity:1; transform:none; } }
`;

/* ─── Main Page ────────────────────────────────────────────────────── */
const Invoices = () => {
  const [allInvoices,  setAllInvoices]  = useState([]);
  const [loading,      setLoading]      = useState(true);
  const [search,       setSearch]       = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [page,         setPage]         = useState(1);
  const [toast,        setToast]        = useState(null);

  const showToast = (msg, type = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get("/api/Invoice/provider");
      const items = Array.isArray(res.data) ? res.data : (res.data?.items ?? []);
      setAllInvoices(items);
    } catch {
      showToast("Failed to load invoices.", "danger");
    } finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const filtered = allInvoices.filter(inv => {
    const s = search.toLowerCase();
    const matchSearch = !search ||
      (inv.invoiceNumber || "").toLowerCase().includes(s) ||
      (inv.patientName   || "").toLowerCase().includes(s);
    const invStatus = inv.invoiceStatus || "Generated";
    const matchStatus = statusFilter === "All" || invStatus === statusFilter;
    return matchSearch && matchStatus;
  });

  const totalCount  = filtered.length;
  const totalPages  = Math.max(1, Math.ceil(totalCount / PAGE_SIZE));
  const visible     = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const handleSearch = (val) => { setSearch(val); setPage(1); };
  const handleStatus = (val) => { setStatusFilter(val); setPage(1); };

  const formatDate = (d) => {
    if (!d) return "—";
    return new Date(d).toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" });
  };

  /* stat totals */
  const totalRevenue = allInvoices.reduce((s, i) => s + (i.totalAmount ?? 0), 0);
  const paidCount    = allInvoices.filter(i => (i.invoiceStatus || "").toLowerCase() === "paid").length;
  const pendingCount = allInvoices.filter(i => (i.invoiceStatus || "").toLowerCase() === "pending").length;

  const amountClass = (status) => {
    const s = (status || "").toLowerCase();
    if (s === "paid")    return "paid";
    if (s === "pending") return "pending";
    return "";
  };

  const cardClass = (status) => {
    const s = (status || "generated").toLowerCase();
    if (s === "paid")    return "paid";
    if (s === "pending") return "pending";
    return "generated";
  };

  return (
    <Layout role="provider">
      <style>{styles}</style>
      <div className="inv-root">

        {toast && <div className={`inv-toast ${toast.type}`}>{toast.msg}</div>}

        {/* Header */}
        <div className="inv-header">
          <h2>Invoices</h2>
          <p>All invoices generated by your hospital</p>
        </div>

        {/* Stat strip */}
        {!loading && (
          <div className="inv-stats">
            <div className="stat-card">
              <span className="stat-label">Total Invoices</span>
              <span className="stat-value">{allInvoices.length}</span>
              <span className="stat-sub">across all statuses</span>
            </div>
            <div className="stat-card">
              <span className="stat-label">Total Revenue</span>
              <span className="stat-value">₹{totalRevenue.toLocaleString("en-IN")}</span>
              <span className="stat-sub">all invoices</span>
            </div>
            <div className="stat-card">
              <span className="stat-label">Paid</span>
              <span className="stat-value" style={{ color:"var(--green)" }}>{paidCount}</span>
              <span className="stat-sub">invoices settled</span>
            </div>
            <div className="stat-card">
              <span className="stat-label">Pending</span>
              <span className="stat-value" style={{ color:"var(--amber)" }}>{pendingCount}</span>
              <span className="stat-sub">awaiting payment</span>
            </div>
          </div>
        )}

        {/* Toolbar */}
        <div className="inv-toolbar">
          {STATUSES.map(s => (
            <button key={s} className={`status-pill ${statusFilter === s ? "active" : ""}`}
              onClick={() => handleStatus(s)}>{s}</button>
          ))}
          <div className="inv-search">
            <Search size={14} />
            <input placeholder="Search by invoice # or patient…" value={search}
              onChange={e => handleSearch(e.target.value)} />
          </div>
        </div>

        {/* Cards */}
        {loading ? (
          <div className="inv-loading"><div className="spinner" /> Loading invoices…</div>
        ) : visible.length === 0 ? (
          <div className="inv-empty">
            <FileText size={40} />
            <p style={{ margin: 0, fontWeight: 600 }}>No invoices found</p>
            <p style={{ margin: ".3rem 0 0", fontSize: ".82rem" }}>Try adjusting your filters or search.</p>
          </div>
        ) : (
          <div className="inv-grid">
            {visible.map(inv => (
              <div key={inv.invoiceId} className={`inv-card ${cardClass(inv.invoiceStatus)}`}>
                <div className="inv-card-top">
                  <span className="inv-number">{inv.invoiceNumber || `#${inv.invoiceId}`}</span>
                  <StatusBadge status={inv.invoiceStatus || "Generated"} />
                </div>

                <div className="inv-meta">
                  <div className="inv-meta-row">
                    <User size={13} />
                    <strong>{inv.patientName || "—"}</strong>
                  </div>
                  <div className="inv-meta-row">
                    <Hash size={13} />
                    Invoice ID: {inv.invoiceId}
                  </div>
                </div>

                <div className="inv-card-footer">
                  <div className="inv-date-chip">
                    <Calendar size={12} />
                    {formatDate(inv.invoiceDate)}
                  </div>
                  <span className={`inv-amount-badge ${amountClass(inv.invoiceStatus)}`}>
                    <IndianRupee size={12} />
                    {(inv.totalAmount ?? 0).toLocaleString("en-IN")}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Paginator */}
        {!loading && visible.length > 0 && (
          <div style={{ marginTop: "1.25rem" }}>
            <Paginator page={page} totalPages={totalPages} totalCount={totalCount}
              pageSize={PAGE_SIZE} onPageChange={setPage} />
          </div>
        )}

      </div>
    </Layout>
  );
};

export default Invoices;
